Source: https://github.com/leosmigel/analyzingalpha/blob/master/sp500-historical-components-and-changes/sp500_constituents_and_history.ipynb

Basically does not work and needs to be worked on to make it work properly... I'll do this some other time (dd. 3/9/21). Not important for the project at this point... Just good to know it can be done.

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

In [14]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
data = pd.read_html(url)

In [15]:
len(data)

2

In [20]:
sp500 = data[0]
sp500

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M Company,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",1976-08-09,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie Inc.,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands Inc,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [21]:
sp500.columns

Index(['Symbol', 'Security', 'SEC filings', 'GICS Sector', 'GICS Sub-Industry',
       'Headquarters Location', 'Date first added', 'CIK', 'Founded'],
      dtype='object')

In [23]:
sp500_changes = data[1]
sp500_changes

                  Date  Added                           Removed  \
                  Date Ticker                  Security  Ticker
0    February 12, 2021   MPWR  Monolithic Power Systems     FTI
1     January 21, 2021   TRMB              Trimble Inc.     CXO
2      January 7, 2021   ENPH            Enphase Energy     TIF
3    December 21, 2020   TSLA               Tesla, Inc.     AIV
4     October 12, 2020    NaN                       NaN     NBL
..                 ...    ...                       ...     ...
260   December 5, 2000    SBL       Symbol Technologies      OI
261   December 5, 2000    AYE          Allegheny Energy     GRA
262   December 5, 2000    ABK           Ambac Financial     CCK
263      July 27, 2000   JDSU              JDS Uniphase     RAD
264   December 7, 1999   YHOO                    Yahoo!     LDW

                                        \
                              Security
0                           TechnipFMC
1                     Concho Resources
2                        Tiffany & Co.
3    Apartment Investment & Management
4                         Noble Energy
..                                 ...
260                     Owens-Illinois
261                         W.R. Grace
262                     Crown Holdings
263                            RiteAid
264                            Laidlaw

                                                Reason
                                                Reason
0    TechnipFMC was removed from the S&P 500 in ant...
1    S&P 500/100 constituent ConocoPhillips acquire...
2    LVMH Moet Hennessy-Louis Vuitton SE acquired T...
3    Apartment Investment and Management (Aimco) sp...
4                   Chevron acquired Noble Energy.[10]
..                                                 ...
260                                Market Cap changes.
261                                Market Cap changes.
262                                Market Cap changes.
263                            Market Cap change.[209]
264                            Market Cap change.[210]

[265 rows x 6 columns]

In [24]:
sp500_changes.columns

MultiIndex([(   'Date',     'Date'),
            (  'Added',   'Ticker'),
            (  'Added', 'Security'),
            ('Removed',   'Ticker'),
            ('Removed', 'Security'),
            ( 'Reason',   'Reason')],
           )

In [26]:
sp500_changes.columns = [ 'Date', 'Added_Ticker', 'Added_Name', 'Removed_Ticker', 'Removed_Name', 'Reason']
sp500_changes.columns

Index(['Date', 'Added_Ticker', 'Added_Name', 'Removed_Ticker', 'Removed_Name',
       'Reason'],
      dtype='object')

In [27]:
sp500_changes

,Date,Added_Ticker,Added_Name,Removed_Ticker,Removed_Name,Reason
0,"February 12, 2021",MPWR,Monolithic Power Systems,FTI,TechnipFMC,TechnipFMC was removed from the S&P 500 in ant...
1,"January 21, 2021",TRMB,Trimble Inc.,CXO,Concho Resources,S&P 500/100 constituent ConocoPhillips acquire...
2,"January 7, 2021",ENPH,Enphase Energy,TIF,Tiffany & Co.,LVMH Moet Hennessy-Louis Vuitton SE acquired T...
3,"December 21, 2020",TSLA,"Tesla, Inc.",AIV,Apartment Investment & Management,Apartment Investment and Management (Aimco) sp...
4,"October 12, 2020",NaN,NaN,NBL,Noble Energy,Chevron acquired Noble Energy.[10]
...,...,...,...,...,...,...
260,"December 5, 2000",SBL,Symbol Technologies,OI,Owens-Illinois,Market Cap changes.
261,"December 5, 2000",AYE,Allegheny Energy,GRA,W.R. Grace,Market Cap changes.
262,"December 5, 2000",ABK,Ambac Financial,CCK,Crown Holdings,Market Cap changes.
263,"July 27, 2000",JDSU,JDS Uniphase,RAD,RiteAid,Market Cap change.[209]
264,"December 7, 1999",YHOO,Yahoo!,LDW,Laidlaw,Market Cap change.[210]

In [31]:
sp500.loc[sp500['Date first added'].isnull()]

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
121,ED,Consolidated Edison,reports,Utilities,Electric Utilities,"New York, New York",NaN,1047862,1823
125,GLW,Corning Inc.,reports,Information Technology,Electronic Components,"Corning, New York",NaN,24741,1851
133,DHR,Danaher Corp.,reports,Health Care,Health Care Equipment,"Washington, D.C.",NaN,313616,1969
134,DRI,Darden Restaurants,reports,Consumer Discretionary,Restaurants,"Orlando, Florida",NaN,940944,1938
149,D,Dominion Energy,reports,Utilities,Electric Utilities,"Richmond, Virginia",NaN,715957,1983
159,ETN,Eaton Corporation,reports,Industrials,Electrical Components & Equipment,"Dublin, Ireland",NaN,1551182,1911
176,ES,Eversource Energy,reports,Utilities,Multi-Utilities,"Hartford, Connecticut",NaN,72741,1966
189,FITB,Fifth Third Bancorp,reports,Financials,Regional Banks,"Cincinnati, Ohio",NaN,35527,1858
190,FE,FirstEnergy Corp,reports,Utilities,Electric Utilities,"Akron, Ohio",NaN,1031296,1997
203,BEN,Franklin Resources,reports,Financials,Asset Management & Custody Banks,"San Mateo, California",NaN,38777,1947
204,FCX,Freeport-McMoRan Inc.,reports,Materials,Copper,"Phoenix, Arizona",NaN,831259,1912
209,GE,General Electric,reports,Industrials,Industrial Conglomerates,"Boston, Massachusetts",NaN,40545,1892
237,HUM,Humana Inc.,reports,Health Care,Managed Health Care,"Louisville, Kentucky",NaN,49071,1961
238,HBAN,Huntington Bancshares,reports,Financials,Regional Banks,"Columbus, Ohio",NaN,49196,1866
268,K,Kellogg Co.,reports,Consumer Staples,Packaged Foods & Meats,"Battle Creek, Michigan",NaN,55067,1906
274,KLAC,KLA Corporation,reports,Information Technology,Semiconductor Equipment,"Milpitas, California",NaN,319201,1975/1977 (1997)
283,LEG,Leggett & Platt,reports,Consumer Discretionary,Home Furnishings,"Carthage, Missouri",NaN,58492,1883
292,L,Loews Corp.,reports,Financials,Multi-line Insurance,"New York, New York",NaN,60086,1959
300,MAR,Marriott International,reports,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","Bethesda, Maryland",NaN,1048286,1927
305,MKC,McCormick & Co.,reports,Consumer Staples,Packaged Foods & Meats,"Hunt Valley, Maryland",NaN,63754,1889
308,MCK,McKesson Corp.,reports,Health Care,Health Care Distributors,"Irving, Texas",NaN,927653,1833
311,MET,MetLife Inc.,reports,Financials,Life & Health Insurance,"New York, New York",NaN,1099219,1868
323,MCO,Moody's Corp,reports,Financials,Financial Exchanges & Data,"New York, New York",NaN,1059556,1909
324,MS,Morgan Stanley,reports,Financials,Investment Banking & Brokerage,"New York, New York",NaN,895421,1935
326,MSI,Motorola Solutions Inc.,reports,Information Technology,Communications Equipment,"Chicago, Illinois",NaN,68505,1928 (2011)
338,NI,NiSource Inc.,reports,Utilities,Multi-Utilities,"Merrillville, Indiana",NaN,1111711,1912
340,NTRS,Northern Trust Corp.,reports,Financials,Asset Management & Custody Banks,"Chicago, Illinois",NaN,73124,1889
352,OMC,Omnicom Group,reports,Communication Services,Advertising,"New York, New York",NaN,29989,1986
359,PAYX,Paychex Inc.,reports,Information Technology,Data Processing & Outsourced Services,"Penfield, New York",NaN,723531,1971
370,PNW,Pinnacle West Capital,reports,Utilities,Multi-Utilities,"Phoenix, Arizona",NaN,764622,1985
375,PPL,PPL Corp.,reports,Utilities,Electric Utilities,"Allentown, Pennsylvania",NaN,922224,1920
387,QCOM,Qualcomm,reports,Information Technology,Semiconductors,"San Diego, California",NaN,804328,1985
391,RTX,Raytheon Technologies,reports,Industrials,Aerospace & Defense,"Waltham, Massachusetts",NaN,101829,1922
399,ROK,Rockwell Automation Inc.,reports,Industrials,Electrical Components & Equipment,"Milwaukee, Wisconsin",NaN,1024478,1903
404,SPGI,S&P Global Inc.,reports,Financials,Financial Exchanges & Data,"New York, New York",NaN,64040,1917
410,SRE,Sempra Energy,reports,Utilities,Multi-Utilities,"San Diego, California",NaN,1032208,1998
420,SBUX,Starbucks Corp.,reports,Consumer Discretionary,Restaurants,"Seattle, Washington",NaN,829224,1971
421,STT,State Street Corp.,reports,Financials,Asset Management & Custody Banks,"Boston, Massachusetts",NaN,93751,1792
429,TROW,T. Rowe Price Group,reports,Financials,Asset Management & Custody Banks,"Baltimore, Maryland",NaN,1113169,1937
431,TPR,"Tapestry, Inc.",reports,Consumer Discretionary,"Apparel, Accessories & Luxury Goods","New York, New York",NaN,1116132,2017
438,TXN,Texas Instruments,reports,Information Technology,Semiconductors,"Dallas, Texas",NaN,97476,1930
450,TSN,Tyson Foods,reports,Consumer Staples,Packaged Foods & Meats,"Springdale, Arkansas",NaN,100493,1935
453,USB,U.S. Bancorp,reports,Financials,Diversified Banks,"Minneapolis, Minnesota",NaN,36104,1968
463,VLO,Valero Energy,reports,Energy,Oil & Gas Refining & Marketing,"San Antonio, Texas",NaN,1035002,1980
471,VIAC,ViacomCBS,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,813828,2019 (1952)
475,VNO,Vornado Realty Trust,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,1982
482,WM,Waste Management Inc.,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968
483,WAT,Waters Corporation,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958
490,WRK,WestRock,reports,Materials,Paper Packaging,"Atlanta, Georgia",NaN,1732845,2015
491,WY,Weyerhaeuser,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,1900
492,WHR,Whirlpool Corp.,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911
497,XRX,Xerox,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,1770450,2017 (1906)

In [32]:
len(sp500.loc[sp500['Date first added'].isnull()])

52

In [29]:
# # Get current S&P table and set header column
# sp500 = data[0].loc[1:,[0,1,6,7]]
# columns = ['added_ticker', 'name', 'date', 'cik']
# sp500.columns = columns
# sp500.loc[sp500['date'].isnull(), 'date'] = '1957-01-01'

# # One date is in the wrong format. Correcting it.
# sp500.loc[~sp500['date'].str.match('\d{4}-\d{2}-\d{2}'), 'date'] = '1985-01-01'
# sp500.loc[:,'date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d'))
# sp500 = pd.melt(sp500, id_vars=['date', 'name', 'cik'], value_vars=['added_ticker'])
# sp500.head()

In [ ]:
# sp500_adjustments = data[1]
# sp500_adjustments = sp500_adjustments[2:].copy()
# columns = ['date', 'added_ticker', 'added_name', 'removed_ticker', 'removed_name', 'reason']
# sp500_adjustments.columns = columns
# updates = sp500_adjustments[~sp500_adjustments['date'].str.contains(',')].T.shift(1).T
# sp500_adjustments['date'].loc[~sp500_adjustments['date'].str.contains(',')] = np.nan
# sp500_adjustments[sp500_adjustments['added_ticker'].isnull()]
# sp500_adjustments.update(updates)
# sp500_adjustments['date'].loc[sp500_adjustments['date'].isnull()] = sp500_adjustments['date'].T.shift(1).T
# sp500_adjustments['date'].loc[sp500_adjustments['date'].isnull()] = sp500_adjustments['date'].T.shift(1).T
# sp500_adjustments['date'].loc[sp500_adjustments['date'].isnull()] = sp500_adjustments['date'].T.shift(1).T
# sp500_adjustments['date'].loc[sp500_adjustments['date'].isnull()] = sp500_adjustments['date'].T.shift(1).T
# sp500_adjustments['date'].loc[sp500_adjustments['date'].isnull()] = sp500_adjustments['date'].T.shift(1).T
# sp500_additions = sp500_adjustments[~sp500_adjustments['added_ticker'].isnull()]
# sp500_additions = sp500_additions[['date', 'added_ticker', 'added_name']]
# sp500_additions.rename(columns={'added_name': 'name'}, inplace=True)
# sp500_additions = pd.melt(sp500_additions, id_vars=['date','name'], value_vars=['added_ticker'])
# sp500_deletions = sp500_adjustments[~sp500_adjustments['removed_ticker'].isnull()]
# sp500_deletions = sp500_deletions[['date', 'removed_ticker', 'removed_name']]
# sp500_deletions.rename(columns={'removed_name': 'name'}, inplace=True)
# sp500_deletions = pd.melt(sp500_deletions, id_vars=['date','name'], value_vars=['removed_ticker'])

# sp500_history = pd.concat([sp500_deletions, sp500_additions])
# sp500_history.head()

In [ ]:
# df = pd.concat([sp500, sp500_history], ignore_index=True)
# df['date'] = pd.to_datetime(df['date'])
# df.sort_values(by='cik', ascending=False, inplace=True)
# deduped_df = df[~df.duplicated(['date', 'variable', 'value'])].copy()
# deduped_df.sort_values(by='date',inplace=True)
# deduped_df.to_csv("sp500_history.csv")
# deduped_df.head()

In [28]:
# deduped_df.sort_values(by='cik', ascending=False, inplace=True)
# deduped_df = deduped_df[~deduped_df.duplicated('value')]
# # discovery has 2 share classes listed
# deduped_df = deduped_df[~deduped_df.duplicated('cik')]
# deduped_df.sort_values(by='value', inplace=True)
# deduped_df.drop(['date', 'variable'], axis=1, inplace=True)
# deduped_df.rename(columns={'value':'ticker'}, inplace=True)
# deduped_df.to_csv("sp500_constituents.csv")
# deduped_df.head()